// Placeholder icons - TODO: replace with proper icon library
export const Icons = {
  Dashboard: '📊',
  Home: '🏠',
  Projects: '📁',
  Tasks: '✅',
  Issues: '⚠️',
  Timeline: '🕐',
  Model3D: '🗺️',
  Map: '🗺️',
  Field: '🗺️',
  Money: '💰',
  Budget: '💰',
  Shopping: '🛒',
  Documents: '📁',
  Quality: '🛡️',
  Analytics: '📊',
  Chart: '📊',
  Trending: '📈',
  CRM: '📈',
  Add: '➕',
  Edit: '✏️',
  Delete: '🗑️',
  View: '👁️',
  Search: '🔍',
  Upload: '⬆️',
  Download: '⬇️',
  Settings: '⚙️',
  Notifications: '🔔',
  Email: '📧',
  User: '👤',
  People: '👥',
  Team: '👥',
  Menu: '☰',
  Close: '✕',
  Folder: '📁',
  Tag: '🏷️',
  Calendar: '📅',
  Clock: '🕐',
  Star: '⭐',
  Logout: '🚪',
};

export default Icons;
