// Ícones simplificados usando Iconoir
import {
  HomeSimple,
  CheckSquare,
  WarningTriangle,
  Map,
  DollarCircle,
  ShoppingBag,
  Shield,
  BarChart,
  TrendingUp,
  Plus,
  Edit,
  Trash,
  Eye,
  Search,
  Upload,
  Download,
  Settings,
  Bell,
  Mail,
  User,
  Group,
  Menu,
  Close,
  Folder,
  Tag,
  Calendar,
  Clock,
  Star,
  LogOut,
} from 'iconoir-react';

export const Icons = {
  Dashboard: HomeSimple,
  Home: HomeSimple,
  Projects: Folder,
  Tasks: CheckSquare,
  Issues: WarningTriangle,
  Timeline: Clock,
  Model3D: Map,
  Map: Map,
  Field: Map,
  Money: DollarCircle,
  Budget: DollarCircle,
  Shopping: ShoppingBag,
  Documents: Folder,
  Quality: Shield,
  Analytics: BarChart,
  Chart: BarChart,
  Trending: TrendingUp,
  CRM: TrendingUp,
  Add: Plus,
  Edit: Edit,
  Delete: Trash,
  View: Eye,
  Search: Search,
  Upload: Upload,
  Download: Download,
  Settings: Settings,
  Notifications: Bell,
  Email: Mail,
  User: User,
  People: Group,
  Team: Group,
  Menu: Menu,
  Close: Close,
  Folder: Folder,
  Tag: Tag,
  Calendar: Calendar,
  Clock: Clock,
  Star: Star,
  Logout: LogOut,
};

export default Icons;
