name: Issue Labeler

on:
    issues:
        types: [opened, edited]
    pull_request_target:
        types: [opened, edited]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    label-issues:
        runs-on: ubuntu-latest
        steps:
            - name: Label bugs
              if: contains(github.event.issue.title, '[Bug]') || contains(github.event.pull_request.title, '[Bug]')
              uses: actions/github-script@v7
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['bug']
                      });

            - name: Label features
              if: contains(github.event.issue.title, '[Feature]') || contains(github.event.pull_request.title, '[Feature]')
              uses: actions/github-script@v7
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['enhancement']
                      });

            - name: Label docs
              if: contains(github.event.issue.title, '[Docs]') || contains(github.event.pull_request.title, '[Docs]')
              uses: actions/github-script@v7
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['documentation']
                      });

            - name: Label performance
              if: contains(github.event.issue.title, '[Performance]') || contains(github.event.pull_request.title, '[Performance]')
              uses: actions/github-script@v7
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['performance']
                      });

            - name: Label security
              if: contains(github.event.issue.title, '[Security]') || contains(github.event.pull_request.title, '[Security]')
              uses: actions/github-script@v7
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: issueNumber,
                        labels: ['security']
                      });
